# Generated by Django 3.1.7 on 2021-03-18 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=50, verbose_name='Логин')),
                ('user_password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Электронная почта')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('prof_pic', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Аватарка')),
                ('github_url', models.CharField(blank=True, max_length=150, verbose_name='Ссылка на GitHub')),
                ('gitlab_url', models.CharField(blank=True, max_length=150, verbose_name='Ссылка на GitLab')),
                ('vk_url', models.CharField(blank=True, max_length=150, verbose_name='Ссылка на VK')),
            ],
        ),
    ]
