# Generated by Django 3.1.7 on 2021-03-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0002_auto_20210318_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_projects', models.CharField(default='Отсутствует', max_length=200, verbose_name='Избранные проекты')),
            ],
            options={
                'verbose_name': 'Избранный проект',
                'verbose_name_plural': 'Избранные проекты',
            },
        ),
        migrations.CreateModel(
            name='FavUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_users', models.CharField(default='Отсутствует', max_length=200, verbose_name='Избранные пользователи')),
            ],
            options={
                'verbose_name': 'Избранный пользователь',
                'verbose_name_plural': 'Избранные пользователи',
            },
        ),
        migrations.CreateModel(
            name='PartProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_projects', models.CharField(default='Отсутствует', max_length=200, verbose_name='Проекты, в которыхучаствует')),
            ],
            options={
                'verbose_name': 'Проект, в котором участвует',
                'verbose_name_plural': 'Проекты, в которых участвует',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='fav_projects',
            field=models.ManyToManyField(to='site_pages.FavProjects'),
        ),
        migrations.AddField(
            model_name='user',
            name='fav_users',
            field=models.ManyToManyField(to='site_pages.FavUsers'),
        ),
        migrations.AddField(
            model_name='user',
            name='part_projects',
            field=models.ManyToManyField(to='site_pages.PartProjects'),
        ),
    ]
