# Generated by Django 3.1.7 on 2021-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0003_auto_20210318_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fav_projects',
            field=models.ManyToManyField(blank=True, to='site_pages.FavProjects'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fav_users',
            field=models.ManyToManyField(blank=True, to='site_pages.FavUsers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='part_projects',
            field=models.ManyToManyField(blank=True, to='site_pages.PartProjects'),
        ),
    ]
