# Generated by Django 3.1.7 on 2021-04-04 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_area', models.CharField(blank=True, max_length=100, verbose_name='Сфера деятельности')),
            ],
            options={
                'verbose_name': 'Сфера деятельности',
                'verbose_name_plural': 'Сферы деятельности',
            },
        ),
        migrations.CreateModel(
            name='FavProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_projects', models.CharField(default='Отсутствует', max_length=200, verbose_name='Избранные проекты')),
            ],
            options={
                'verbose_name': 'Избранный проект',
                'verbose_name_plural': 'Избранные проекты',
            },
        ),
        migrations.CreateModel(
            name='FavUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_users', models.CharField(default='Отсутствует', max_length=200, verbose_name='Избранные пользователи')),
            ],
            options={
                'verbose_name': 'Избранный пользователь',
                'verbose_name_plural': 'Избранные пользователи',
            },
        ),
        migrations.CreateModel(
            name='PartProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_projects', models.CharField(default='Отсутствует', max_length=200, verbose_name='Проекты, в которых участвует')),
            ],
            options={
                'verbose_name': 'Проект, в котором участвует',
                'verbose_name_plural': 'Проекты, в которых участвует',
            },
        ),
        migrations.CreateModel(
            name='PartUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проекта',
            },
        ),
        migrations.CreateModel(
            name='ProfSkills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_skills', models.CharField(blank=True, max_length=100, verbose_name='Профессиональный навык')),
            ],
            options={
                'verbose_name': 'Профессиональный навык',
                'verbose_name_plural': 'Профессиональные навыки',
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(blank=True, max_length=100, verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Квалификация',
                'verbose_name_plural': 'Квалификации',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, default='Участник', max_length=100)),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователя',
            },
        ),
        migrations.AddField(
            model_name='advuser',
            name='github_url',
            field=models.URLField(blank=True, max_length=150, verbose_name='Ссылка на GitHub'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='gitlab_url',
            field=models.URLField(blank=True, max_length=150, verbose_name='Ссылка на GitLab'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='prof_pic',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Аватарка'),
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_area', models.ManyToManyField(blank=True, default='Отсутствует', to='main.ActiveArea', verbose_name='Сфера деятельности')),
                ('prof_skills', models.ManyToManyField(blank=True, default='Отсутствуют', to='main.ProfSkills', verbose_name='Профессиональные навыки')),
                ('qualification', models.ManyToManyField(blank=True, default='Отсутствует', to='main.Qualification', verbose_name='Квалификация')),
            ],
            options={
                'verbose_name': 'Технология программирования',
                'verbose_name_plural': 'Технологии программирования',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=50, verbose_name='Описание проекта')),
                ('contacts', models.CharField(blank=True, max_length=100, verbose_name='Контакты для связи с командой разработки')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания проекта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('project_logo', models.ImageField(blank=True, upload_to='logos/%Y/%m/%d/', verbose_name='Логотип(картинка) проекта')),
                ('creator_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель проекта')),
                ('part_users', models.ManyToManyField(blank=True, default='Отсутствуют', to='main.PartUsers', verbose_name='Участники проекта')),
                ('technologies', models.ManyToManyField(blank=True, default='Отсутствуют', to='main.Technologies', verbose_name='Используемые технологии')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.AddField(
            model_name='partusers',
            name='part_users',
            field=models.ManyToManyField(default='Отсутствуют', to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта'),
        ),
        migrations.AddField(
            model_name='partusers',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='main.roles', verbose_name='Роль в проекте'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=250, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Дата создания комментария')),
                ('project_html', models.URLField(blank=True, max_length=150, verbose_name='Ссылка на проект')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Проект, о котором оставлен комментарий')),
                ('user_id', models.ForeignKey(default='Пользователь удалён', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь, оставивший комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='advuser',
            name='fav_projects',
            field=models.ManyToManyField(blank=True, to='main.FavProjects', verbose_name='Избранные проекты'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='fav_users',
            field=models.ManyToManyField(blank=True, to='main.FavUsers', verbose_name='Избранные пользователи'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='part_projects',
            field=models.ManyToManyField(blank=True, to='main.PartProjects', verbose_name='Проекты, в которых участвует'),
        ),
    ]
